---
collections:
  - name: ansible.netcommon
    version: "8.7.1"
    source: https://galaxy.ansible.com
  - name: ansible.utils
    version: "6.1.1"
    source: https://galaxy.ansible.com
  - name: community.general
    version: "13.5.0"
    source: https://galaxy.ansible.com
  - name: moreati.jq
    version: "0.2.1"
    source: https://galaxy.ansible.com
  - name: https://github.com/jahknem/nokia.isam.git
    type: git
    version: "0.3.5"
  - name: netbox.netbox
    version: "3.23.0"
